### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Stella-Hoshineko** [djfdat/AudioBookBay-Magnet-Assistant#2]
The firefox addon doesn't seem to work for me. I think the only issue is that the website changed its url since then ?

Updating the manifest.json will be enough, but perhaps using audiobookbay.* instead of .fi would make the addon more futureproof, anticipating further mirror changes ?

**Comment by djfdat** [comment]
Hey! Unfortunately, I don't think it's that easy, Firefox requires that the domain name + tld is explicitly listed in the manifest. Wildcards can only be used before and after that part of the URL. I will do a pass to update the URLs in the manifest and push an update. Thanks for notifyiing me!

**Comment by djfdat** [comment]
Pushed new extension version w/ additional TLDs. Please let me know in the future if there are any other TLDs that I'm missing!
