### ISSUE TITLE
audiobookbay.se

### ISSUE THREAD

**Issue by seanbuckley** [djfdat/AudioBookBay-Magnet-Assistant#4]
In my location, [audiobookbay.se](https://audiobookbay.se) is working, while [audiobookbay.is](https://audiobookbay.is) is not. It would be great to have support for `.se` again. Can you re-enable that TDL?

**Comment by djfdat** [comment]
Shoot, didn't realize that one was still working. I'll get this fixed soon. Sorry for the inconvenience.

**Comment by djfdat** [comment]
Should be fixed in 3bdac9d

Resubmitted addon to Firefox Addons as well, v 1.0.4 should be approved and available with this fix.
