### ISSUE TITLE
audiobookbay.lu

### ISSUE THREAD

**Issue by seanbuckley** [djfdat/AudioBookBay-Magnet-Assistant#6]
Extension doesn't appear to be configured to work with [audiobookbay.lu](audiobookbay.lu). Are you able to add this domain? Thanks

**Comment by djfdat** [comment]
Sure thing! I’ll try to get this done today.

**Comment by jstraten** [comment]
Same issue. Is this already fixed? How can I get the corrected version? Thank you!

**Comment by djfdat** [comment]
Fixed in afe8734. Just submitted the update to Firefox Addons, you should see the update soon! Thanks for bringing this to my attention@
